export interface EndUserProfile {
     userID : string,
     username : string,
     userType: string,
     dateCreated : string,
     lastActive : string,
     firstName : string,
     lastName : string,
     password : string,
     email : string,

     streetNo : string,
     streetName : string,
     city : string,
     state : string,
     country : string,
     homeNo : string,
     mobileNo : string,
     birthDay : number,
     birthMonth : number,
     birthYear : number,
     purchaseCount : number,
     voucherCount : number,
     familySize : number,
     active : boolean,
     deletionPeriod : string
}